version: "3.9"
services:
  app:
    build: .
    ports:
      - "3001:3000"
    links:
      - db
    networks:
      - default
    volumes:
      - ./app:/home/app
  db:
    image: mysql:8.0.30-oracle
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: pweb_pizarra
      MYSQL_ROOT_PASSWORD: pwdRoot
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./conf:/etc/mysql/conf.d
      - mysql-node:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    links:
      - db:db
    ports:
      - 9000:80
    environment:
      MYSQL_ROOT_PASSWORD: pwdRoot
volumes:
  mysql-node:
